weights: /bwopt/MODELS/hj/VL/yolo-insulator/insulator_yolo/artifacts/runs/baseline_gpu_clean/weights/best.pt
source: /bwopt/MODELS/hj/VL/data/insulator-defect-detection/Test_IDID/Test
conf: 0.4
iou: 0.5
max_det: 100
classes:
  - 1
  - 2
save: true
project: /bwopt/MODELS/hj/VL/yolo-insulator/insulator_yolo/artifacts/runs
name: predict_defects_only
